version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - db_data_fontes:/postgres
    restart: always
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
    networks:
      - backend

  cache:
    image: redis:latest
    volumes:
      - db_data_fontes:/cache
    restart: always
    env_file:
      - ./cache.env
    ports:
      - "6379:6379"
    networks:
      - backend

  api:
    container_name: fontesApi
    depends_on:
      - db
      - cache
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always
    env_file:
      - ./.env
    networks:
      - backend

volumes:
  db_data_fontes: {}
networks:
  backend:
    driver: bridge
